name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-test:
    strategy:
      matrix:
        java-version: [ 8, 11 ]
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}

      - name: Setup coursier cache
        uses: coursier/cache-action@v6

      - name: Install sbt
        run: |
          curl -Ls https://git.io/sbt > ./sbt
          chmod 0755 ./sbt

      - name: Test
        run: ./sbt test
